version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./data:/var/www/html/data
    working_dir: /var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
