name: CI

on: [push, pull_request]

jobs:
  php-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo_sqlite
      - name: Install dependencies (none)
        run: echo 'No composer dependencies for this demo'
      - name: Create data dir
        run: mkdir -p data
      - name: Run DB smoke test
        run: php db/test_db.php
